### ISSUE TITLE
Launch Issues

### ISSUE THREAD

**Issue by KosnIre** [Sajo8/turtlecoin-block-bot#1]
1. [✓] method to get block hash only returns the hash of the last tx in that block 
2. [✓] only tx extra for last tx returned -- [Taco]
3. [✓] no tx_extra value returned; payment id thing returned is invalid -- [Sajo] 
4. [✓] error handling for json decode error and connection error -- [rashedmyt]

**Comment by Sajo8** [comment]
Thanks again

**Comment by Sajo8** [comment]
#2 Fixes this, thank you so much!

**Comment by KosnIre** [comment]
Looks like this is fixed by #2 so I'm closing this issue :+1:

**Comment by Sajo8** [comment]
Yup, thank you for all your contributions!
